### PR TITLE
Updated to released xunit 2.0

### PR DESCRIPTION
**Pull request by mattridgway**

### CODE REVIEW

**Comment by rhysgodfrey** [comment]
Thanks @mattridgway and @herecydev!

The changes to the build script and project format will mean that the CI build needs to be updated, I will try and take a look at that when I get chance and merge this in if everything goes well :)

**Comment by rhysgodfrey** [comment]
This PR brings the code onto a supported version which should hopefully address #2.

**Comment by mattridgway** [comment]
Thanks @rhysgodfrey !

**Comment by memark** [comment]
What is the status on this?

**Comment by rhysgodfrey** [comment]
Hi @memark,

Apologies, lost this Pull Request.

There is an alternative plugin as part of the [JetBrains Power Pack](https://github.com/JetBrains/meta-runner-power-pack/tree/master/xunit.net), unless anybody thinks there is value in continuing with this alternative plugin aswell, I'm tempted to update this project to redirect people to the Power Pack alternative. This already has some features such as running tests against multiple assemblies and dotCover integration which this plugin doesn't have.

Thanks,
Rhys

**Comment by memark** [comment]
Hi!

No worries. Thanks, I'll have a look at the Power Pack instead. A redirect sounds reasonable.

/M

On 29 sep. 2015, at 23:20, Rhys Godfrey <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @memark<https://github.com/memark>,

Apologies, lost this Pull Request.

There is an alternative plugin as part of the JetBrains Power Pack<https://github.com/JetBrains/meta-runner-power-pack/tree/master/xunit.net>, unless anybody thinks there is value in continuing with this alternative plugin aswell, I'm tempted to update this project to redirect people to the Power Pack alternative. This already has some features such as running tests against multiple assemblies and dotCover integration which this plugin doesn't have.

Thanks,
Rhys

-

**Pull request closed without merging**
